### ISSUE TITLE
Add the ability to edit Install Order Notes

### ISSUE THREAD

**Issue by meyer-mcmains** [matortheeternal/mod-picker-issues#10]
It might be useful to have the ability to edit Install Order Notes after you have submitted, in order to fix grammatical errors or formatting issues. (this probably also applies to Load Order Notes, and Compatibility Notes)

**Comment by matortheeternal** [comment]
UGH, this bug is still present?

We have editing fully built into the platform for all contributions, but the action doesn't display in the dropdown due to some stupid bug.  UGH!  Pisses me off.  >_>'

Stupid code.

**Comment by matortheeternal** [comment]
Issues resolved, hotfixed on the server.  Thank you very much for reporting this.  I think it was fixed, and then broke again.  I fixed it for good this time.
