### ISSUE TITLE
Account password change error

### ISSUE THREAD

**Issue by surilindur** [matortheeternal/mod-picker-issues#11]
An error message seems to be displayed when trying to change the account password. Changing the toggle options in "other" work, but password change always fails, no matter how simple or complex the password, and it fails even if the password were just as long as the old one. The error is this (appears on red background, when success messages appear in a similar fashion but with green background):

`Error saving user registration, 422: Unprocessable Entity`

The browser is Mozilla Firefox, version 50.0 (but it also happened with a previous browser version), and I have tried all sorts of password candidates, even ones with only characters A-Z and numbers 0-9, so it is most likely not about the password itself.

Has anyone else run into any similar issues?

**Comment by matortheeternal** [comment]
This happens if you were sent an invite to the beta and didn't accept it.

**Comment by surilindur** [comment]
Ah, okay. Sorry for the late reply. I went to my email inbox and clicked the beta invite link, after which I was able to successfully change my password without issues. Thank you, I would not have thought about it myself.

So the issue is now solved. It was not really an issue with Mod Picker, then, just me not clicking a link.

**Comment by matortheeternal** [comment]
Glad you got into your account!

We invalidated all of the old invitations at some point a week ago because too many people were running into this issue.  You probably ended up creating a new account (which is fine).  👍
