### ISSUE TITLE
"Submit A Skyrim Mod" 404 Error

### ISSUE THREAD

**Issue by KerningChameleon** [matortheeternal/mod-picker-issues#12]
Clicking on the "Submit A Skyrim Mod" button in the header toolbar returns a 404 error. [First time on Firefox 50.1.0](https://puu.sh/sWyi8/2625f37cb9.png) on Windows 10 64-Bit (1607). Tried again on SRWare Iron (54.0.2850.0, Chromium variant, out of date because I don't need to use it much) without any prior site cookies, still got a 404 error.

**Comment by matortheeternal** [comment]
Issue resolved.  We had a route precedence error that was introduced when we made the site viewable without being logged in.
