### ISSUE TITLE
Mod Submission Error when submitting "Elemental Destruction Magic"

### ISSUE THREAD

**Issue by KerningChameleon** [matortheeternal/mod-picker-issues#13]
When attempting to submit ["Elemental Destruction Magic"](http://www.nexusmods.com/skyrim/mods/69474/) [(Steam Workshop page](http://steamcommunity.com/sharedfiles/filedetails/?id=534403432)) in Firefox 50.1.0 on Windows 10 64-Bit (1607), Mod Picker throws the following error:

> There were errors submitting your mod.
> undefined local variable or method `mod' for #<ModBuilder:0x007f05890cb9e0>
> Click here to return to the submission form

I scrape the Steam Workshop page before the Nexus page so that the Nexus details are what gets automatically filled in in the General Info fields. This is what my submission page looks like when attempting to submit the mod:

![](https://puu.sh/t3mqq/6f3dddf412.png)
![](https://puu.sh/t3mtz/0f10fa8a47.png)
![](https://puu.sh/t3mvm/8bf20470d8.png)
![](https://puu.sh/t3mCe/75e2ec58b8.png)

**Comment by matortheeternal** [comment]
Did you try clicking submit a second time?  Sometimes this error is erratic.

**Comment by matortheeternal** [comment]
The error message was actually due to an error in the error handling.  Something else caused the error.  If you try submitting again it should give a different error message.

**Comment by matortheeternal** [comment]
Alright, found the issue - it's related to some kind of failed Date comparison.  I'm looking into the root cause.

**Comment by matortheeternal** [comment]
Issue resolved.

**Comment by matortheeternal** [comment]
Mod available at: https://modpicker.com/skyrim#/mod/1353
