### ISSUE TITLE
More Bandit Camps: Error scraping Nexus Mods mod page, Duplicate entry '1994' for key 'PRIMARY'

### ISSUE THREAD

**Issue by megaloblast** [matortheeternal/mod-picker-issues#14]
Error scraping Nexus Mods mod page, Duplicate entry '1994' for key 'PRIMARY'
When trying to add More Bandit Camps
http://www.nexusmods.com/skyrimspecialedition/mods/1994/?

**Comment by matortheeternal** [comment]
Hotfixed ~10 hours ago.  :+1:
