### ISSUE TITLE
Broken sort options on Mods Index

### ISSUE THREAD

**Issue by lizenas** [matortheeternal/mod-picker-issues#16]
OS: Currently Chromebook, but the same issue occurs on macOS and Windows 10, using Google Chrome.
Steps: On the Skyrim or Skyrim SE page, click Browse Skyrim/Skyrim SE mods, click any category, then sort mods by:

- Primary Category
- Secondary Category
- Endorsements
- Subscribers
- Unique DLs
- Favorites
- Downloads
- Views
- Posts
- Images
- Videos
- Files
- Bugs
- Discussions
- Articles

![500 error](https://cloud.githubusercontent.com/assets/8002234/23566767/257c7cd2-0008-11e7-81b7-c4904e860ca4.png)

**Comment by matortheeternal** [comment]
Thank you for the report, I'll get this fixed ASAP!

**Comment by matortheeternal** [comment]
I've fixed the majority of the problem.  The following two sort options will still not work:

- Primary Category
- Secondary Category

I'll be fixing those next!

**Comment by matortheeternal** [comment]
I resolved that sorting by the name of the category isn't really useful, and removed the sort option instead.
