### ISSUE TITLE
Add option to disable the greybeard and dog popup

### ISSUE THREAD

**Issue by lizenas** [matortheeternal/mod-picker-issues#18]
Dear god please

**Comment by matortheeternal** [comment]
You can hide the helper at any time by clicking the "X" in the corner.  This will apply to the current tab as you navigate through the site unless you reload the page.

![](http://puu.sh/uHLhR.jpg)

If you have an account you can check "Disable helper by default" in the "Other" section of your [Account Settings](https://modpicker.com/skyrim/settings/account).  This will cause the helper to be hidden by default on every page.

![](http://puu.sh/uHL9q.png)

**Comment by lizenas** [comment]
Oh. Well I feel dumb

**Comment by matortheeternal** [comment]
All good man.  :)
