### ISSUE TITLE
cant change avatar "need -10.789 more reputation"

### ISSUE THREAD

**Issue by spaceoden** [matortheeternal/mod-picker-issues#19]
![capture](https://cloud.githubusercontent.com/assets/26421479/23927161/5e64f7ce-08d5-11e7-9907-c2dff6418727.PNG)

**Comment by matortheeternal** [comment]
fixed with a page refresh I'm guessing?

I'll see if I can make it so it doesn't require a page refresh.  :+1:

**Comment by spaceoden** [comment]
iirc page refresh wasn't enough, but waiting a few minutes resolved it.

**Comment by matortheeternal** [comment]
Might have been caching then.  I'll poke around in my development environment and see if I can recreate this.
