### ISSUE TITLE
Add "works well with" and "supersedes" to Compatibility or Requirements

### ISSUE THREAD

**Issue by LunaticNeko** [matortheeternal/mod-picker-issues#2]
Some mods, like [Legacy of the Dragonborn](http://www.nexusmods.com/skyrim/mods/52248/?), do not explicitly require other mods, but can work well with them in many ways. This kind of compatibility do not require any patch. Additionally, the mod can actively use the content from the other mods at the same time. LotD [supersedes or fully integrates, for example, Moonpath to Elsweyr](http://legacy-of-the-dragonborn.wikia.com/wiki/Moonpath_to_Elsweyr), while having "works well with" compatibility level with others.

In my humble opinion, please add two more compatibility levels:
- X works well with Y: X actively interacts with the content of Y without requiring any patches.
- X supersedes Y: X either fully integrates Y, or has an absolutely larger set of features or functionality than Y. Use with Y is not recommended.

**Comment by matortheeternal** [comment]
This is a good suggestion!  I'll have to think it over a bit more before making a final decision, but it sounds very good!  Thank you for you contribution.

**Comment by emiliadmcclure** [comment]
I realize this issue is over a month old, but just wanted to add that I love this suggestion and suggest to maybe implement it with a section like "Recommended To Use With this Mod" on the mod's page? 

For example, while Hypothermia/iNeed aren't required by Frostfall, a lot of people recommend one or the other for the "hardcore realism" aspect.

**Comment by matortheeternal** [comment]
Hi @devonrmcclure.  Yeah, I actually was just charting out a new feature for the site to add a "Related Mods" section with
- Alternative mods (mods that offer similar functionality that should not be used with the mod)
- Recommended Mods (mods that work well with the mod or offer similar functionality)

The way this would work is a user would submit a "Related Mod Note".  For this they would:
- Specify a mod to recommend/as an alternative
- Provide a short description about why they're recommending it/how it might be an alternative

I envision this working similar to [recommendations on MyAnimeList](https://myanimelist.net/anime/1827/Seirei_no_Moribito/userrecs), though I don't know if we'll allow multiple people to make the same recommendations with their own descriptions (we would just attach helpful/not helpful marks to recommendations instead).

**Comment by matortheeternal** [comment]
Feature is complete, just need to deploy it.

![Submission screenshot](http://puu.sh/tWkGf.jpg)
![Related Mod Note display](http://puu.sh/tWkRv.jpg)

**Comment by matortheeternal** [comment]
Added in v1.4.
