### ISSUE TITLE
Error when Submitting Load Order Note

### ISSUE THREAD

**Issue by EniracY** [matortheeternal/mod-picker-issues#20]
When trying to submit a LO Note for Archery Gameplay Overhaul and Ordinator, I receive this error: _'Error submitting Load Order Note, undefined local variable or method `second_plugin' for #<LoadOrderNote:0x007f473a4baef0> Did you mean? second_plugin_filename'_

Note when choosing Ordinator, several .esp options show.
![mod picker error 2](https://cloud.githubusercontent.com/assets/26751372/24427505/0e670c2e-1403-11e7-9982-034bb14ce54d.jpg)
![mod picker error](https://cloud.githubusercontent.com/assets/26751372/24427506/0e6b0248-1403-11e7-926c-3899a1b47e4f.JPG)

**Comment by matortheeternal** [comment]
Alright, will resolve ASAP!

**Comment by matortheeternal** [comment]
Fixed both issues.  :+1:

Thank you!
