### ISSUE TITLE
If you search for a mod without having saved your mod list, you are unable to cancel the serach.

### ISSUE THREAD

**Issue by Shybert** [matortheeternal/mod-picker-issues#21]
1. Make a change to your mod list
2. Search for something

When you search, the search page will load before you are asked if you want to leave the page or not. If you press "Cancel" on this screen, the box will just go away, deleting the progress you have made with your mod list.
![image](https://cloud.githubusercontent.com/assets/25749775/24585179/4b71ef9c-1784-11e7-87ab-78c322743998.png)
The picture shows that I can see the "Unsaved changes" box, yet I have already left my mod list page.

**Comment by matortheeternal** [comment]
Thanks for the report!  Will look into it.

**Comment by matortheeternal** [comment]
Got this resolved on dev, will push a hotfix.

**Comment by matortheeternal** [comment]
Verified resolved on production.  :+1:

Thanks again for the report Shybert.
