### ISSUE TITLE
 Frostfall 3.0: Error scraping Nexus Mods mod page, that mod has been hidden by the author or site staff. 

### ISSUE THREAD

**Issue by direinsomniac** [matortheeternal/mod-picker-issues#22]
Tried to submit the Frostfall 3.0 mod by chesko but got the above error message.

I found it odd that I was finding patches and other mods related to Frostfall, but not the mod itself.

**Comment by matortheeternal** [comment]
The mod is currently hidden, and may be restored at a future date.
