### ISSUE TITLE
Moddata not autoupdating

### ISSUE THREAD

**Issue by jotoho** [matortheeternal/mod-picker-issues#23]
I have semi-recently heard about Modpicker and checked it out today, but I have noticed, as I searched for one of my favourite Skyrim Mods, that Better Vampires is still named as Version 7.95 even though the Modauthor changes the Modtitle on Nexus every time he updates and on a closer look it seems that Modpicker has neither updated the Title nor "Date Updated" from Nexusmods.  I would like to see Modpicker regulary checking if the Modtitle or other information has changed on the source site and update, if necessary, to avoid possible confusion. Just wanted to make sure you knew about it.

**Comment by matortheeternal** [comment]
We're aware of this.  There is an auto-scraper bot coded but it hasn't been running on schedule.  Will be resolved soon.

**Comment by matortheeternal** [comment]
Resolved.
