### ISSUE TITLE
Date field doesn't work with firefox

### ISSUE THREAD

**Issue by dreadflopp** [matortheeternal/mod-picker-issues#24]
When submitting a new mod with a custom source using firefox, the date-fields doesn't work. The format letters (mm/dd/yyyy) doesn't show up and dates with the correct formats are not accepted. On chrome using the same pc it works fine.

Edit: Mod is for SSE, using windows 10.

**Comment by matortheeternal** [comment]
Firefox can support date fields, but you have to manually activate it.  Go to `about:config` and find the field `dom.forms.datetime`, then toggle it to true.

![](http://puu.sh/wuOdh.png)

**Comment by matortheeternal** [comment]
I did not realize Firefox did not enable this input type by default, so I'll set up a polyfill so it can work even if the input type is not available.

**Comment by dreadflopp** [comment]
Thanks, changing the setting in firefox fixed it.

**Comment by matortheeternal** [comment]
Closed for the time being, will have an update coming soon which offers a custom date-picker when the user's browser does not have it enabled.
