### ISSUE TITLE
Merged plugins that has the original .esp (the ones that were merged) flagged as masters (Skyrim)

### ISSUE THREAD

**Issue by PoorUnluckyOne** [matortheeternal/mod-picker-issues#26]
I have just recently discovered the wonders on merging many mods into only a few. Also, I have been away of Skyrim for at least a year, so I was expecting to have everything prepared before I started again. I rescued Mod Organizer, Wyre Bash, TES5edit and so on, and installed Merged Plugins. After watching GamerPoets tutorial, read almost every guide out there, being warned about merges that dont work and watching videos about how it should be done, I started to make my merges: armor pack, weapon pack, map, merge plugins of a single mod... After I was satisfied with my merges, I started to uncheck the individual and old plugins to enable the new merge (using M.O.).

Then, I was horrified to discover a warning at the right of that the merged plugin name that said that it has masterfiles missing. How could it be? None of the merged mods needed a master other than the Skyrim .esm. The master files missing are the plugings of the mods I just merged together. A armor merge that still needs the plugins of the Stormlord armor, Talos Housecarl, Triss outfit... enabled in order to work.

I followed each and every step provided by the Nexus page, the STEP guide, the GamerPoets youtube video, rebuilding merges again doing other things, following again the guides, touching the .ini files... everything. Even the logs says that all went well (all the merge logs says: "adding masters... done adding masters", so no master were added in any merge), but this artificial master file dependency goes on. I have gone desperate for help, even to ask for it in the tutorial video. Not even my father, a true magician of the Net and the Motherboards, found the root of this problem.

Here I left a list with my merges and the .esp that they have inside, perhaps this can help:

Pack de Armaduras (armor pack): bikini armor, Triss armor, Baraban steel helms, Baraban steel plate, baraban dawnguard, talos housecarl, armor of intrigue, Stormlord, cloaks of skyrim, cloaks dawnguard, bandolier
 
Pack de armas (weapon pack): Billyros weapons, Merc nord shields, ceremonial greatsword, historically acurate weapons, MGsword, Loners sword, unique uniques.
 
Lugares mejorados (enhanced locations): better morthal/ravenrock/dawnstar/docks of solitude , complete skyforge, winterhold gate, riverwood gate, underforge entrance, beakcoast cave star wars easter egg
 
Realistic waters two: five .esp less the main one, it seems that people in the forums says that it must not be merged
 
Estética (aestetics): eyes of beauty, brows, beards. 
 
Map Merged: quality world map (icepenguin), Atlas legendary, atlas compass
 
Bijin + Seranaholic: bijin warmaidens, bijin wives, bijin npc, seranaholic serana, seranaholic valerica
 
Combat evolved: core esp, enemy poison, magic and spell, stealth
 
RealisticNights: realisticnights.esp, realisticnightsDG.esp, realisticnightsDG.esp 

Please, help me...

![merge plugins problema](https://user-images.githubusercontent.com/34317358/33681533-2313c1e2-dac5-11e7-8a50-a60e48e34f3a.jpg
![tes5edit screen](https://user-images.githubusercontent.com/34317358/33681552-3418553e-dac5-11e7-8640-fca7d6fbc168.png)
)

**Comment by matortheeternal** [comment]
Replied to your message on STEP.

I'm certain this is one of the following:

1. Using a translation borking the merging process (has been a bug in the past, not sure if fixed in the build you're using)
2. Not using merge method "overrides".
