### ISSUE TITLE
Lovers Lab account linking issue

### ISSUE THREAD

**Issue by Liviu-Sorin-Rusu** [matortheeternal/mod-picker-issues#27]
As the title says.

I enabled the status updates, copied the profile url, but the verify button remains grayed out....

**Comment by matortheeternal** [comment]
Should be fixed now.  Let me know if the problem persists!

**Comment by matortheeternal** [comment]
Looking into it.

**Comment by matortheeternal** [comment]
Lover's Lab updated fairly recently, so some things have changed, I've recreated this issue in my local environment and I'll have it fixed soon.

**Comment by matortheeternal** [comment]
Alright, appears to be fixed for me.  Let me know if it works for you!

**Comment by Liviu-Sorin-Rusu** [comment]
Yep, it's fixed and thanks.
Also wanted to say, the site is awesome as it reminds me of GEMS (gameplay enhancements mods for skyrim) and PCPartPicker :)

**Comment by matortheeternal** [comment]
Glad to hear you like the site, thank you!

The site was largely inspired by PCPartPicker.  :)
