### ISSUE TITLE
Selecting a mod from the Ajax query does nothing

### ISSUE THREAD

**Issue by angrmgmt** [matortheeternal/mod-picker-issues#3]
I assume it's Ajax, anyway.  Either way, typing the name of a mod properly searches live and returns results, but clicking them in the drop-down has no effect.  The highlight appears on mouseover, but clicking simply dismisses the drop-down with no effect on the mod list.  I am using Chrome 53.0.2785.143 m (64-bit) on Windows 10, 64bit, Version 1607 (including "anniversary update").

ETA:  Might as well note I'm on the Mods tab of my mod list trying to add mods to it!
Edit2:  Fixed Chrome version, forgot about update.  Issue stands.

**Comment by matortheeternal** [comment]
Will investigate, thank you!

**Comment by angrmgmt** [comment]
No problem, let me know if you need anything else from me!

**Comment by angrmgmt** [comment]
More testing reveals that it depends WHERE in the dropdown item I click.  There is a box around the center that does not accept clicks.  The center and the edges of the highlighted item are clickable, but that middle area isn't.

Something like the following screenshot, but I'm not sure of the exact bounds.  The red area is unclickable.
![noclick](https://cloud.githubusercontent.com/assets/7545532/19134802/1766ec44-8b15-11e6-9fba-1b572534df0d.png)

**Comment by matortheeternal** [comment]
That's very odd...

**Comment by angrmgmt** [comment]
Agreed.  I can only imagine there is some CSS arcanery (or some other, less vile Lovecraftian horror) causing a border property to run amok.  Chrome Dev Console cannot find it to highlight, though.  I hate front-end stuff, so I don't envy you - that delve into F12 gave me enough heebies for one day.

**Comment by matortheeternal** [comment]
This should have been resolved in the [v0.8 update](https://gist.github.com/matortheeternal/e90b8486908a6e35da4739fcc52ef770).  Please let me know if the bug still happens for you @angrmgmt.
