### ISSUE TITLE
Add Mod button showing for mod already in Modlist

### ISSUE THREAD

**Issue by MacSplody** [matortheeternal/mod-picker-issues#30]
https://i.imgur.com/fC6khFr.png 

I added the mod from inside the edit modlist section, and when I went to view it the option to add was still showing.

**Comment by matortheeternal** [comment]
could be due to caching or if you had opened the mod page prior to adding it to your mod list.

the remove button appears to be visible just fine when I add a mod to my mod list and then navigate to its page.
