### ISSUE TITLE
Deleted List & Mod list count

### ISSUE THREAD

**Issue by MacSplody** [matortheeternal/mod-picker-issues#38]
Deleted lists will still count towards a Mods total mod lists.

![image](https://user-images.githubusercontent.com/1944639/40693474-78b1df26-63af-11e8-83bc-c02ab181eda5.png)

**Comment by matortheeternal** [comment]
I think this is expected behavior until the mod list is actually purged from the database.

**Comment by MacSplody** [comment]
Okay, thought deleted lists would not count towards it. I'll mark it as closed if that's how it was meant to be working.
