### ISSUE TITLE
The browse mods page does not properly list/display my mods

### ISSUE THREAD

**Issue by praxis22** [matortheeternal/mod-picker-issues#4]
According to my Mod List, I have 44 mods but only 5 plugins, yet on the Browse Skyrim mods page, it say I have only 5 mods and five plugins. One because I just added Interesting NPC's, The rest are Masters. The list of Skyrim mods also does not list my installed mods, though it does complain if I try to add it again, so it knows that I have more than 5 mods, it just doesn't display this fact.

I expect you'll fix it in due course.

**Comment by matortheeternal** [comment]
Try reloading the mods index to see if that updates the counts.  Sometimes that can get out-of-sync with your mod list itself - this is a bug we're aware of.  I think that is the entirety of your issue, but I'm not sure without a screenshot.  Let me know if that fixes your problems.

Regards,
\- Mator

**Comment by praxis22** [comment]
Cheers Mator, already tried that, doesn't work. Also the buttons don't update, the only ones that are lit, are the base masters, and 3DNPC once I ckicked add. The other 43, they still say "add" and complain it already exists if you click it again, but still doesn't update.

**Comment by matortheeternal** [comment]
What browser are you using?  This is very odd behavior.

**Comment by praxis22** [comment]
At home I'm using a (fairly heavily modified) version of Firefox, (latest release) . By which I mean ad-blocking, Anti-tracking, privacy mods, test-pilot, etc.  Javascript is unmolested, and I have no problems with most sites. I've also got about 400 tabs open, (though only a few active) I can try with other browsers, but they also locked down, privacy/tracking & ad-dblocking wise.

I should mention that after a lot of back and forth, testing yesterday, after a few different refreshes, and reloads, I did eventually get it to update the mod count. And show which mods I had installed in the list. I might have a dig into the CSS later.

**Comment by matortheeternal** [comment]
No one else has reported this bug, and I have yet to see it happen in my development or production environments.  For now I'm going to chalk this up to your setup and close it.  If the bug is still happening please let me know @praxis22
