### ISSUE TITLE
Declutter the header

### ISSUE THREAD

**Issue by user19410** [matortheeternal/mod-picker-issues#40]
Two thirds of the mod list page are currently occupied by headers/bars. It would be preferable to have a more compact design to increase productivity.

**Currently there are 6 bars:**
1. Mod Picker | Welcome user | Alerts | My Contributions | Settings | Log Out | Skyrim
2. Manage Your Mod Lists | View Recent Contributions | Browse Mod Lists | Browse Skyrim Mods | Submit a Skyrim Mod
3. User's Mod List by User | Created .. | Updated .. | Actions | Status
4. Details | Tools | Mods | Plugins | Config | Analysis | Comments
5. Unresolved Issues | Ignored Issues | Missing Requirements
6. Mods | Grid View | Sort Install Order | Add Group | Add Custom Mod

**Suggestions:**
1. Remove the picture of the mountains from the header and move it to the sides of the main section.
2. Merge bars 1 and 2 so that it looks something like this:
	Mod Picker | Manage Lists | Recent Contribs | Browse | Submit Mod | Account | Alerts | Skyrim
Browse Lists and Browse Mods would be merged into Browse.
Account would contain a menu with Profile, My Contributions, Settings, Log Out
A button with the icon of a magnifying glass could be added in this header so that when you click on it a Search Box appears and occupies all or part of the bar, and the cursor could be already focused inside of it ready to type.
3. Merge headers 3 and 5: Header 5 contains very few information, and header 3 occupies a lot of space. They could be compacted into one.
4. Merge headers 4 and 6. The tags in header 4 could be reduced a bit, and be placed immediately above of the List. The buttons in header 6 could have shorter names: 
	Grid/List | Sort | + Group | + Custom Mod

**Comment by matortheeternal** [comment]
This sounds like a very large stylistic change and isn't something I can see happening any time in the near future.  I don't see the amount of horizontal bars as a serious deterrent to viewing, they take up only half of a 1080p page view.  Whether or not it's "good" or "bad" design doesn't really matter to me, it's functional.  There are much more pressing things currently, such as improving the plugin load order sorting UX (and fixing the issues with the drag and drop becoming slow as balls when there are too many mods/plugins present).

The usage of a large number of full-width horizontal sections also isn't necessarily uncommon.  Large parts of Mod Picker's UX were inspired by PCPartPicker, and [the Build Guides on their site](https://pcpartpicker.com/guide/t832FT/great-amd-gaming-build) have a similar "issue" with "content" starting halfway down the page.
