### ISSUE TITLE
Incorrect Count Displayed in Number of Reviews

### ISSUE THREAD

**Issue by angrmgmt** [matortheeternal/mod-picker-issues#5]
On the mod page for Deadly Dragons, the counter on the reviews tab shows there is a review, but the list is empty and states that no reviews exist.

Here's a screenshot:
![noreviewsbutthis 1](https://cloud.githubusercontent.com/assets/7545532/19134578/a48c7e24-8b13-11e6-8d41-e1dedaba4dbf.png)

**Comment by matortheeternal** [comment]
This count is not _actually_ incorrect, there's just a review that has not been approved.

Ideally these counts should be updated when reviews are approved/unapproved hidden/unhidden.

**Comment by angrmgmt** [comment]
Cool, man.  Wondered if maybe it was something like that.  Hope it helps!

**Comment by matortheeternal** [comment]
Resolved in v0.9.
