### ISSUE TITLE
View more mods by same source uploader from Mod Authors modal

### ISSUE THREAD

**Issue by Xgatt** [matortheeternal/mod-picker-issues#6]
It would be better it clicking on their name takes the user to a page listing the author's mods. This is what we currently get: http://imgur.com/a/VppsM

**Comment by matortheeternal** [comment]
I don't think the modal should be replaced - it does serve an explicit purpose.  However, I can add a link to the modal to view more mods by the same uploader.

**Comment by Xgatt** [comment]
Sure. Why does it say "no one is assigned as an author" though? Shouldn't it list Pfuscher there?

**Comment by matortheeternal** [comment]
Resolved in latest update.  http://puu.sh/sfQ7N.png
