### ISSUE TITLE
Modal Dialog Missing for Add Custom Mod

### ISSUE THREAD

**Issue by angrmgmt** [matortheeternal/mod-picker-issues#7]
Clicking the "+ Add Custom Mod" button appears to want to start a modal dialog for entry, but instead creates a blank "Custom Mod", disables input, dims the page and removes the scroll bar, and waits for input that never arrives:

![image](https://cloud.githubusercontent.com/assets/7545532/19214283/f4d09e2a-8d33-11e6-91e3-2e79c15ea480.png)

Windows 10 x64 v1607, Chrome 53.0.2785.143 m (64-bit).

**Comment by matortheeternal** [comment]
This was resolved in a recent platform update, [v0.8](https://gist.github.com/matortheeternal/e90b8486908a6e35da4739fcc52ef770).
