### ISSUE TITLE
Unable to meet requirement for SKSE

### ISSUE THREAD

**Issue by Xgatt** [matortheeternal/mod-picker-issues#8]
If there are any mods requiring SKSE (and, by extension, any other tool I assume), that requirement is never marked as met. 

To reproduce:
1. Add SkyUI to modlist and save.
2. Under the requirements section, you will see that SKSE is unmet. Click to add SKSE and save. You will find it under tools.
3. Under Mods, SKSE remains an unmet requirement. I'm guessing stuff under "tools" isn't being counted under met requirements. 

Also, the error message is unable to catch the name of SKSE when trying to re-add. It says, "Error adding mod, mod_id: The mod is already present on the mod list." The ", mod_id" part usually contains the mod name.

**Comment by matortheeternal** [comment]
This was resolved in the [v0.8 update](https://gist.github.com/matortheeternal/e90b8486908a6e35da4739fcc52ef770).
